#

In [28]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [55]:
titanic_data = pd.read_csv("titanic.csv")
titanic_data.describe()
titanic_data = pd.get_dummies(titanic_data, columns=["Sex"])
titanic_data = pd.get_dummies(titanic_data,columns=["Embarked"])
mean_age = titanic_data['Age'].mean()
titanic_data["Age"].fillna(value=mean_age,inplace=True)
mean_fare = titanic_data['Fare'].mean()
titanic_data["Fare"].fillna(value=mean_fare,inplace=True)
titanic_data


PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name       Age  SibSp  Parch  \
0                                Kelly, Mr. James  34.50000      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  47.00000      1      0   
2                       Myles, Mr. Thomas Francis  62.00000      0      0   
3                                Wirz, Mr. Albert  27.00000      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  22.00000      1      1   
..                                            ...       ...    ...    ...   
413                            Spector, Mr. Woolf  30.27259      0      0   
414                  Oliva y Ocana, Dona. Fermina  39.00000      0      0   
415                  Saether, Mr. Simon Sivertsen  38.50000      0      0   
416                           Ware, Mr. Frederick  30.27259      0      0   
417                      Peter, Master. Michael J  30.27259      1      1   

                 Ticket      Fare Cabin  Sex_female  Sex_male  Embarked_C  \
0                330911    7.8292   NaN           0         1           0   
1                363272    7.0000   NaN           1         0           0   
2                240276    9.6875   NaN           0         1           0   
3                315154    8.6625   NaN           0         1           0   
4               3101298   12.2875   NaN           1         0           0   
..                  ...       ...   ...         ...       ...         ...   
413           A.5. 3236    8.0500   NaN           0         1           0   
414            PC 17758  108.9000  C105           1         0           1   
415  SOTON/O.Q. 3101262    7.2500   NaN           0         1           0   
416              359309    8.0500   NaN           0         1           0   
417                2668   22.3583   NaN           0         1           1   

     Embarked_Q  Embarked_S  
0             1           0  
1             0           1  
2             1           0  
3             0           1  
4             0           1  
..          ...         ...  
413           0           1  
414           0           0  
415           0           1  
416           0           1  
417           0           0  

[418 rows x 15 columns]

In [56]:
titanic_data["Fare"].isnull().values.any()

False

In [57]:
x = titanic_data.iloc[:,[0,2,4,5,6,8,10,11,12,13,14]].values
y = titanic_data.iloc[:,1].values
x

array([[8.92000000e+02, 3.00000000e+00, 3.45000000e+01, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [8.93000000e+02, 3.00000000e+00, 4.70000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [8.94000000e+02, 2.00000000e+00, 6.20000000e+01, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       ...,
       [1.30700000e+03, 3.00000000e+00, 3.85000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [1.30800000e+03, 3.00000000e+00, 3.02725904e+01, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [1.30900000e+03, 3.00000000e+00, 3.02725904e+01, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [62]:
from sklearn.model_selection import  train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=10,test_size=.2)


array([[1.17300000e+03, 3.00000000e+00, 7.50000000e-01, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [9.44000000e+02, 2.00000000e+00, 2.00000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [1.19500000e+03, 3.00000000e+00, 2.40000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       ...,
       [9.07000000e+02, 2.00000000e+00, 2.40000000e+01, ...,
        1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.01700000e+03, 3.00000000e+00, 1.70000000e+01, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [1.15700000e+03, 3.00000000e+00, 3.02725904e+01, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [63]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [68]:
from sklearn.ensemble import RandomForestClassifier

regressor = RandomForestClassifier(random_state=0, n_estimators=10)
regressor.fit(x_train, y_train) 


RandomForestClassifier(n_estimators=10, random_state=0)

In [70]:
y_pred = regressor.predict(x_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [0 0]]


In [71]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[45  0]
 [ 0 39]]


1.0